# Generated by Django 4.1.4 on 2022-12-28 10:48

from django.db import migrations, models

import app.models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_rename_realease_date_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_to),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_to),
        ),
    ]
