# Generated by Django 4.1.4 on 2023-01-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_movie_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_rating',
            field=models.FloatField(default=models.FloatField()),
        ),
    ]
